name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "31 22 * * 1"

env:
  NODE_VERSION: 18

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependency
        run: |
          npm install

      - name: Code test
        run: npm run test
